'use client'

import { motion } from 'framer-motion'
import { useState } from 'react'

interface FAQItemProps {
  question: string
  answer: string
  index: number
}

function FAQItem({ question, answer, index }: FAQItemProps) {
  const [isOpen, setIsOpen] = useState(false)

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.5, delay: index * 0.1 }}
      className="card-modern overflow-hidden"
    >
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full px-6 py-5 flex items-center justify-between text-left hover:bg-gray-50 transition-colors"
      >
        <span className="text-lg font-semibold text-brand-dark font-primary pr-4">
          {question}
        </span>
        <motion.span
          animate={{ rotate: isOpen ? 180 : 0 }}
          transition={{ duration: 0.3 }}
          className="text-2xl text-brand-blue flex-shrink-0"
        >
          ↓
        </motion.span>
      </button>
      
      <motion.div
        initial={false}
        animate={{
          height: isOpen ? 'auto' : 0,
          opacity: isOpen ? 1 : 0
        }}
        transition={{ duration: 0.3 }}
        className="overflow-hidden"
      >
        <div className="px-6 pb-5 text-brand-gray font-secondary leading-relaxed">
          {answer}
        </div>
      </motion.div>
    </motion.div>
  )
}

export default function FAQSection() {
  const faqs = [
    {
      question: 'What is fractional real estate ownership?',
      answer: 'Fractional ownership means you can buy a portion (fraction) of a property instead of the whole thing. Each fraction represents actual ownership, not just shares or percentages. You receive a unique registration code (PR-HRL-####) and a digital certificate proving your ownership.'
    },
    {
      question: 'How does the payment process work?',
      answer: 'We maintain a strict zero-cash policy. All transactions happen through secure payment links generated by sales agents. Once you confirm your purchase, the payment is processed through bank-grade encrypted gateways, and your ownership is instantly recorded in the system.'
    },
    {
      question: 'What are the three BuyOps apps?',
      answer: 'BuyOps Admin is the governance layer for enterprise management. BuyOps Sales is the velocity layer for agents to manage leads and close deals. BuyOps Investor is the liquidity layer where you can browse properties, buy fractions, and track your portfolio.'
    },
    {
      question: 'Is my investment secure?',
      answer: 'Absolutely. Every property undergoes legal title verification, property valuation, and compliance certification before listing. All transactions are digitally recorded with blockchain-backed verification. Your digital certificate and unique PR-HRL code provide immutable proof of ownership.'
    },
    {
      question: 'What happens after I purchase a fraction?',
      answer: 'Upon successful payment, the system auto-generates your unique Registration Code (PR-HRL-####) and issues a Digital Deed. You gain immediate access to detailed property information, projected returns, and can track your investment through the Investor dashboard.'
    },
    {
      question: 'What fees are involved?',
      answer: 'We believe in transparency. All fees are clearly displayed before purchase, including platform fees, transaction fees, and any property management costs. There are no hidden charges. Everything is priced and settled in Nigerian Naira (₦).'
    }
  ]

  return (
    <section id="faq" className="section-padding bg-gray-50">
      <div className="container-custom">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8 }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl md:text-5xl font-bold text-brand-dark mb-4 font-primary">
            Frequently Asked Questions
          </h2>
          <p className="text-xl text-brand-gray max-w-2xl mx-auto font-secondary">
            Everything you need to know about fractional real estate investment
          </p>
        </motion.div>

        <div className="max-w-3xl mx-auto space-y-4">
          {faqs.map((faq, index) => (
            <FAQItem
              key={index}
              question={faq.question}
              answer={faq.answer}
              index={index}
            />
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8, delay: 0.5 }}
          className="text-center mt-12"
        >
          <p className="text-brand-gray mb-4 font-secondary">Still have questions?</p>
          <button className="px-8 py-3 border-2 border-brand-blue text-brand-blue font-semibold rounded-lg hover:bg-brand-blue hover:text-white transition-all font-secondary">
            Contact Support
          </button>
        </motion.div>
      </div>
    </section>
  )
}
